export const API_AUTH_START = 'API_AUTH_START';
export const API_AUTH_SUCCESS = 'API_AUTH_SUCCESS';
export const API_AUTH_FAILED = 'API_AUTH_FAILED';
export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const VERIFIED = 'VERIFIED';

export const MODAL_SHOW = 'MODAL_SHOW';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_SELLERS = 'GET_ALL_SELLERS';
export const SEARCH_USER_BY_EMAIL = 'SEARCH_USER_BY_EMAIL';
export const FILTER_USER_BY_STATUS = 'FILTER_USER_BY_STATUS';
export const FILTER_SELLER_BY_STATUS = 'FILTER_SELLER_BY_STATUS';
export const SEARCH_SELLER_BY_EMAIL = 'SEARCH_SELLER_BY_EMAIL';

export const BAN_USER = 'BAN_USER';
export const BAN_SELLER = 'BAN_SELLER';
export const UNBAN_USER = 'UNBAN_USER';
export const UNBAN_SELLER = 'UNBAN_SELLER';
export const CHECK_STATUS = 'CHECK_STATUS';
export const GET_SUBMISSION_AUCT = 'GET_SUBMISSION_AUCT';

export const API_START = 'API_START';
export const API_SUCCESS = 'API_SUCCESS';
export const API_FAILED = 'API_FAILED';
export const CONFIRM_SUBMISSION = 'CONFIRM_SUBMISSION';
export const REJECT_SUBMISSION = 'REJECT_SUBMISSION';
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';
export const FETCH_PRODUCT_PAGE = 'FETCH_PRODUCT_PAGE';
export const FETCH_DATA_BY_PRODUCTID = 'FETCH_DATA_BY_PRODUCTID';
export const GET_CATEGORY = 'GET_CATEGORY';
export const FETCH_DATA_BY_CATEGORY = 'FETCH_DATA_BY_CATEGORY';
export const FETCH_DATA_MIN_PRICE = 'FETCH_DATA_MIN_PRICE';
export const FETCH_DATA_MAX_PRICE = 'FETCH_DATA_MAX_PRICE';
export const FETCH_DATA_BY_RANGE_PRICE = 'FETCH_DATA_BY_RANGE_PRICE';
export const FETCH_DATA_BY_CATEGORY_AND_PRICE = 'FETCH_DATA_BY_CATEGORY_AND_PRICE';
export const FETCH_DATA_CATEG_MIN = 'FETCH_DATA_CATEG_MIN';
export const FETCH_DATA_CATEG_MAX = 'FETCH_DATA_CATEG_MAX';
export const FETCH_DATA_BY_NAME = 'FETCH_DATA_BY_NAME';
export const FETCH_DATA_BY_TIME = 'FETCH_DATA_BY_TIME';
export const FETCH_DATA_BY_PRICE = 'FETCH_DATA_BY_PRICE';
export const FETCH_ACTIVE_PRODUCT_PAGE = 'FETCH_ACTIVE_PRODUCT_PAGE';
export const FETCH_PENDING_PRODUCT_PAGE = 'FETCH_PENDING_PRODUCT_PAGE';
export const FETCH_FINISH_PRODUCT_PAGE = 'FETCH_FINISH_PRODUCT_PAGE';

export const GET_SERVER_TIME = 'GET_SERVER_TIME';

export const FILTER_SUBMISSION_BY_STATUS = 'FILTER_SUBMISSION_BY_STATUS';

export const API_PAYMENT_START = 'API_PAYMENT_START';
export const ADD_TOPUP_SUCCESS = 'API_PAYMENT_SUCCESS';
export const API_PAYMENT_FAILED = 'API_PAYMENT_FAILED';
export const GET_TOPUP = 'GET_TOPUP';
export const FILTER_PAYMENT_BY_STATUS = 'FILTER_PAYMENT_BY_STATUS';
export const FILTER_PAYMENT_BY_USERNAME = 'FILTER_PAYMENT_BY_USERNAME';
export const REJECT_TOPUP = 'REJECT_TOPUP';
export const CONFIRM_TOPUP = 'CONFIRM_TOPUP';

export const GET_WALLET_START = 'GET_WALLET_START';
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS';
export const GET_WALLET_FAILED = 'GET_WALLET_FAILED';

export const POST_PRODUCT = 'POST_PRODUCT';
export const API_POST_FAILED = 'API_POST_FAILED';